
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rysk
 */
public class GBMIMSGUI extends javax.swing.JFrame {

    
    //class level variables
    DefaultListModel<String> newOrderCart = new DefaultListModel();
    DefaultListModel<Order> myOrders = new DefaultListModel();
    
    /**
     * Creates new form GBMIMSGUI
     */
    public GBMIMSGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        pnlLogin = new javax.swing.JPanel();
        lblLoginTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txfPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        pnlNewOrder = new javax.swing.JPanel();
        lblNewOrderTitle = new javax.swing.JLabel();
        scpNewOrderInventoryList = new javax.swing.JScrollPane();
        jlstNewOrderInventory = new javax.swing.JList<>();
        scpNewOrderPreview = new javax.swing.JScrollPane();
        jlstNewOrderOrderPreview = new javax.swing.JList<>();
        btnNewOrderLoadInventory = new javax.swing.JButton();
        btnNewOrderAddItem = new javax.swing.JButton();
        btnNewOrderSubmit = new javax.swing.JButton();
        btnNewOrderRemoveItem = new javax.swing.JButton();
        pnlMyOrders = new javax.swing.JPanel();
        lblMyOrdersTitle = new javax.swing.JLabel();
        btnMyOrdersReturn = new javax.swing.JButton();
        scpMyOrdersOrderList = new javax.swing.JScrollPane();
        jlstMyOrders = new javax.swing.JList<>();
        scpMyOrdersPreview = new javax.swing.JScrollPane();
        txaMyOrdersPreview = new javax.swing.JTextArea();
        btnMyOrdersLoadOrders = new javax.swing.JButton();
        pnlOrderLogs = new javax.swing.JPanel();
        lblOrderLogsTitle = new javax.swing.JLabel();
        btnOrderLogsDelete = new javax.swing.JButton();
        scpOrderLogsOrders = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        scpOrderlogsPreview = new javax.swing.JScrollPane();
        txaOrderLogsPreview = new javax.swing.JTextArea();
        btnOrderLogsLoad = new javax.swing.JButton();
        mnbMain = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLoginTitle.setText("GB Manufacturing Inventory Management System");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setText("Username:");
        lblUsername.setToolTipText("");

        txfUsername.setToolTipText("");
        txfUsername.setPreferredSize(new java.awt.Dimension(256, 24));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Password:");
        lblPassword.setToolTipText("");

        txfPassword.setToolTipText("");
        txfPassword.setPreferredSize(new java.awt.Dimension(256, 24));

        btnLogin.setText("Sign In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(352, 352, 352))))
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lblLoginTitle)
                .addGap(0, 109, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginTitle)
                .addGap(174, 174, 174)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        tabMain.addTab("Login", pnlLogin);

        lblNewOrderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNewOrderTitle.setText("New Order");

        jlstNewOrderInventory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scpNewOrderInventoryList.setViewportView(jlstNewOrderInventory);

        jlstNewOrderOrderPreview.setModel(newOrderCart);
        scpNewOrderPreview.setViewportView(jlstNewOrderOrderPreview);

        btnNewOrderLoadInventory.setText("Load/Refresh Inventory");
        btnNewOrderLoadInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderLoadInventoryActionPerformed(evt);
            }
        });

        btnNewOrderAddItem.setText("Add Item");
        btnNewOrderAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderAddItemActionPerformed(evt);
            }
        });

        btnNewOrderSubmit.setText("Submit");
        btnNewOrderSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderSubmitActionPerformed(evt);
            }
        });

        btnNewOrderRemoveItem.setText("Remove Item");
        btnNewOrderRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderRemoveItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewOrderLayout = new javax.swing.GroupLayout(pnlNewOrder);
        pnlNewOrder.setLayout(pnlNewOrderLayout);
        pnlNewOrderLayout.setHorizontalGroup(
            pnlNewOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNewOrderTitle)
                .addGap(336, 336, 336))
            .addGroup(pnlNewOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNewOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewOrderLayout.createSequentialGroup()
                        .addComponent(btnNewOrderLoadInventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                        .addComponent(btnNewOrderAddItem))
                    .addComponent(scpNewOrderInventoryList))
                .addGap(18, 18, 18)
                .addGroup(pnlNewOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scpNewOrderPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlNewOrderLayout.createSequentialGroup()
                        .addComponent(btnNewOrderRemoveItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewOrderSubmit)))
                .addContainerGap())
        );
        pnlNewOrderLayout.setVerticalGroup(
            pnlNewOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNewOrderTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(pnlNewOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scpNewOrderPreview)
                    .addComponent(scpNewOrderInventoryList, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewOrderLoadInventory)
                    .addComponent(btnNewOrderAddItem)
                    .addComponent(btnNewOrderSubmit)
                    .addComponent(btnNewOrderRemoveItem))
                .addGap(70, 70, 70))
        );

        tabMain.addTab("New Order", pnlNewOrder);

        lblMyOrdersTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMyOrdersTitle.setText("My Orders");

        btnMyOrdersReturn.setText("Return");

        jlstMyOrders.setModel(myOrders);
        scpMyOrdersOrderList.setViewportView(jlstMyOrders);

        txaMyOrdersPreview.setColumns(20);
        txaMyOrdersPreview.setRows(5);
        scpMyOrdersPreview.setViewportView(txaMyOrdersPreview);

        btnMyOrdersLoadOrders.setText("Load My Orders");
        btnMyOrdersLoadOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyOrdersLoadOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMyOrdersLayout = new javax.swing.GroupLayout(pnlMyOrders);
        pnlMyOrders.setLayout(pnlMyOrdersLayout);
        pnlMyOrdersLayout.setHorizontalGroup(
            pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyOrdersLayout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addComponent(lblMyOrdersTitle)
                .addGap(336, 336, 336))
            .addGroup(pnlMyOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMyOrdersLayout.createSequentialGroup()
                        .addComponent(btnMyOrdersLoadOrders)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scpMyOrdersOrderList))
                .addGap(18, 18, 18)
                .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpMyOrdersPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMyOrdersReturn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlMyOrdersLayout.setVerticalGroup(
            pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMyOrdersTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scpMyOrdersPreview)
                    .addComponent(scpMyOrdersOrderList, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyOrdersLoadOrders)
                    .addComponent(btnMyOrdersReturn))
                .addGap(70, 70, 70))
        );

        tabMain.addTab("My Orders", pnlMyOrders);

        lblOrderLogsTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOrderLogsTitle.setText("Order Logs");

        btnOrderLogsDelete.setText("Delete Order");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scpOrderLogsOrders.setViewportView(jList3);

        txaOrderLogsPreview.setColumns(20);
        txaOrderLogsPreview.setRows(5);
        scpOrderlogsPreview.setViewportView(txaOrderLogsPreview);

        btnOrderLogsLoad.setText("Load");
        btnOrderLogsLoad.setToolTipText("");
        btnOrderLogsLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderLogsLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOrderLogsLayout = new javax.swing.GroupLayout(pnlOrderLogs);
        pnlOrderLogs.setLayout(pnlOrderLogsLayout);
        pnlOrderLogsLayout.setHorizontalGroup(
            pnlOrderLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLogsLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(lblOrderLogsTitle)
                .addGap(336, 336, 336))
            .addGroup(pnlOrderLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderLogsLayout.createSequentialGroup()
                        .addComponent(btnOrderLogsLoad)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scpOrderLogsOrders))
                .addGap(18, 18, 18)
                .addGroup(pnlOrderLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpOrderlogsPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderLogsDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlOrderLogsLayout.setVerticalGroup(
            pnlOrderLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrderLogsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(pnlOrderLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scpOrderlogsPreview)
                    .addComponent(scpOrderLogsOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrderLogsLoad)
                    .addComponent(btnOrderLogsDelete))
                .addGap(70, 70, 70))
        );

        tabMain.addTab("Order Logs", pnlOrderLogs);

        jMenu1.setText("File");
        mnbMain.add(jMenu1);

        jMenu2.setText("Edit");
        mnbMain.add(jMenu2);

        setJMenuBar(mnbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewOrderLoadInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderLoadInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewOrderLoadInventoryActionPerformed

    private void btnMyOrdersLoadOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyOrdersLoadOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMyOrdersLoadOrdersActionPerformed

    private void btnOrderLogsLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderLogsLoadActionPerformed
        // TODO add your handling code here:
        //get log
        try {
            DataIO data = new DataIO(); // create DataIO object
            //load orders
            ArrayList<Order> logs = data.getOrderList();
            for(int i = 0; i < logs.size(); i++)
            {
                //TODO: DISPLAY
                
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnOrderLogsLoadActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(login())
        {
        tabMain.setSelectedIndex(1);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "ERROR: LOGIN FAILED", "USER AUTH FAILED", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnNewOrderRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderRemoveItemActionPerformed
        //get selected item from list
        String itm = jlstNewOrderOrderPreview.getSelectedValue();
        
        //if something is selected, add it to the order
        if(itm != null)
        {
            newOrderCart.removeElement(jlstNewOrderOrderPreview.getSelectedValue());
        }
    }//GEN-LAST:event_btnNewOrderRemoveItemActionPerformed

    private void btnNewOrderAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderAddItemActionPerformed
        //get selected item from list
        String itm = jlstNewOrderInventory.getSelectedValue();
        
        //if something is selected, add it to the order
        if(itm != null)
        {
            newOrderCart.add(newOrderCart.getSize(), itm);
        }
    }//GEN-LAST:event_btnNewOrderAddItemActionPerformed

    private void btnNewOrderSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderSubmitActionPerformed
        //check if order is empty
        if(newOrderCart.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Error: cart is empty",
                    "Empty Order Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            //if not empty, create order
            Order newOrder = new Order();
            myOrders.add(myOrders.getSize(), newOrder);
            tabMain.setSelectedIndex(2);
            //yay!
            
        }
    }//GEN-LAST:event_btnNewOrderSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GBMIMSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GBMIMSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GBMIMSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GBMIMSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GBMIMSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMyOrdersLoadOrders;
    private javax.swing.JButton btnMyOrdersReturn;
    private javax.swing.JButton btnNewOrderAddItem;
    private javax.swing.JButton btnNewOrderLoadInventory;
    private javax.swing.JButton btnNewOrderRemoveItem;
    private javax.swing.JButton btnNewOrderSubmit;
    private javax.swing.JButton btnOrderLogsDelete;
    private javax.swing.JButton btnOrderLogsLoad;
    private javax.swing.JList<String> jList3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JList<Order> jlstMyOrders;
    private javax.swing.JList<String> jlstNewOrderInventory;
    private javax.swing.JList<String> jlstNewOrderOrderPreview;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblMyOrdersTitle;
    private javax.swing.JLabel lblNewOrderTitle;
    private javax.swing.JLabel lblOrderLogsTitle;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenuBar mnbMain;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlMyOrders;
    private javax.swing.JPanel pnlNewOrder;
    private javax.swing.JPanel pnlOrderLogs;
    private javax.swing.JScrollPane scpMyOrdersOrderList;
    private javax.swing.JScrollPane scpMyOrdersPreview;
    private javax.swing.JScrollPane scpNewOrderInventoryList;
    private javax.swing.JScrollPane scpNewOrderPreview;
    private javax.swing.JScrollPane scpOrderLogsOrders;
    private javax.swing.JScrollPane scpOrderlogsPreview;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextArea txaMyOrdersPreview;
    private javax.swing.JTextArea txaOrderLogsPreview;
    private javax.swing.JTextField txfPassword;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables

    public boolean login() {
        //get username and password from text fields
        String eid = txfUsername.getText();
        String pass = txfPassword.getText();
        
        //try to validate login
        try {
            DataIO data = new DataIO(); // create DataIO object
            //load employees
            ArrayList<Employee> employees = data.getEmployeeList();
            for(int i = 0; i < employees.size(); i++)
            {
                if(employees.get(i).getEmpID() == eid)
                {
                    if(employees.get(i).getPassword().equals(pass))
                    {
                        return true;
                    }
                    else
                    {
                        
                        return false;
                    }
                }
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        
        return false;
    }

    
    
}
